/**
 * The recording script for the final voiceover, apps/video/VOICEOVER.md: every line in order,
 * how it is said, how long the scratch take runs, and where it lands in the film.
 *
 *   pnpm --filter @shakedown/video vo-sheet
 *
 * Run it after `pnpm voice`, so the lengths are the scratch takes' real ones.
 */
import { existsSync, readFileSync, writeFileSync } from 'node:fs'
import path from 'node:path'
import { FPS, lines, SCENES, START } from '../src/script'
import { spoken } from '../src/spoken'
import { anchorsFor, type Take } from '../src/timeline'

const ROOT = path.resolve(import.meta.dirname, '..')
const takeFile = path.join(ROOT, 'public/footage/live-run.json')
const take = existsSync(takeFile) ? (JSON.parse(readFileSync(takeFile, 'utf8')) as Take) : undefined

const clock = (seconds: number) =>
  `${Math.floor(seconds / 60)}:${(seconds % 60).toFixed(1).padStart(4, '0')}`

const out: string[] = [
  '# Voiceover script',
  '',
  'Generated by `pnpm --filter @shakedown/video vo-sheet` from `src/script.ts`; edit the script',
  'there, not here. "Say" is how each line is read aloud. "Scratch" is how long the scratch take',
  '(Kokoro) runs: aim near it, a little slower is fine. "In the film" is where the line starts.',
  '',
  'Record one file per scene, named as in each heading (for example `01-hook.wav`). Read the lines',
  'in order with a one-second pause between them, so they can be cut apart cleanly.',
  '',
]
for (const [i, scene] of SCENES.entries()) {
  const file = `${String(i + 1).padStart(2, '0')}-${scene.id}.wav`
  out.push(`## ${i + 1}. ${scene.title} (\`${file}\`, ${scene.seconds} s)`, '')
  out.push('| # | Line | Say | Scratch | In the film |', '|---|---|---|---|---|')
  for (const line of lines(scene, { anchors: anchorsFor(scene.id, take) })) {
    const said = spoken(line.text)
    out.push(
      `| ${line.sentence + 1} | ${line.text} | ${said === line.text ? '' : said} | ${line.seconds.toFixed(1)} s | ${clock(START[scene.id] / FPS + line.start)} |`,
    )
  }
  out.push('')
}
writeFileSync(path.join(ROOT, 'VOICEOVER.md'), `${out.join('\n')}\n`)
console.log('Wrote VOICEOVER.md.')
