/**
 * The recording script for the final voiceover, apps/video/VOICEOVER.md: every line in order,
 * how it is said, how long the scratch take runs, and where it lands in the film.
 *
 *   pnpm --filter @shakedown/video vo-sheet
 *   pnpm --filter @shakedown/video vo-sheet --film=walkthrough   # VOICEOVER-walkthrough.md
 *
 * Run it after `pnpm voice`, so the lengths are the scratch takes' real ones.
 */
import { writeFileSync } from 'node:fs'
import path from 'node:path'
import { FPS, lines, SCENES, type Scene, START } from '../src/script'
import { spoken } from '../src/spoken'
import { W_SCENES, W_START } from '../src/walkthrough/script'

const ROOT = path.resolve(import.meta.dirname, '..')

const clock = (seconds: number) =>
  `${Math.floor(seconds / 60)}:${(seconds % 60).toFixed(1).padStart(4, '0')}`

const walkthrough = process.argv.includes('--film=walkthrough')
const scenes: readonly Scene[] = walkthrough ? W_SCENES : SCENES
const startOf = (id: string) =>
  walkthrough
    ? ((W_START as Record<string, number>)[id] ?? 0)
    : ((START as Record<string, number>)[id] ?? 0)

const out: string[] = walkthrough
  ? [
      '# Voiceover script: the walkthrough',
      '',
      'Generated by `pnpm --filter @shakedown/video vo-sheet --film=walkthrough` from',
      '`src/walkthrough/script.ts`; edit the script there, not here. Say it the way you would show',
      'a colleague your screen: relaxed and conversational, about as fast as the scratch voice',
      '(around 155 words a minute). The pauses are already in the cut, so read each line on its',
      'own and stop between them; read much slower and the film grows by the difference. "Say" is',
      'how a line is read aloud, "Scratch" how long the scratch take (Kokoro, a male voice) runs,',
      'and "In the film" where the line starts; the pictures follow your voice.',
      '',
      'Record one file per scene, named as in each heading (for example `01-w-intro.wav`), with a',
      'one-second pause between lines, so they can be cut apart cleanly.',
      '',
    ]
  : [
      '# Voiceover script',
      '',
      'Generated by `pnpm --filter @shakedown/video vo-sheet` from `src/script.ts`; edit the script',
      'there, not here. "Say" is how each line is read aloud. "Scratch" is how long the scratch take',
      '(Kokoro) runs; read a little slower than it, at about 145 to 150 words a minute, with no long',
      'pauses: each scene has about half a second to spare. "In the film" is where the line starts, and',
      'the pictures follow the voice, so they move with your reading.',
      '',
      'Record one file per scene, named as in each heading (for example `01-hook.wav`). Read the lines',
      'in order with a one-second pause between them, so they can be cut apart cleanly.',
      '',
    ]
for (const [i, scene] of scenes.entries()) {
  const file = `${String(i + 1).padStart(2, '0')}-${scene.id}.wav`
  out.push(`## ${i + 1}. ${scene.title} (\`${file}\`, ${scene.seconds} s)`, '')
  out.push('| # | Line | Say | Scratch | In the film |', '|---|---|---|---|---|')
  for (const line of lines(scene)) {
    const said = spoken(line.text)
    out.push(
      `| ${line.sentence + 1} | ${line.text} | ${said === line.text ? '' : said} | ${line.seconds.toFixed(1)} s | ${clock(startOf(scene.id) / FPS + line.start)} |`,
    )
  }
  out.push('')
}
const file = walkthrough ? 'VOICEOVER-walkthrough.md' : 'VOICEOVER.md'
writeFileSync(path.join(ROOT, file), `${out.join('\n')}\n`)
console.log(`Wrote ${file}.`)
