// Generated by scripts/gen-toolkit-schema.mjs from @paypal/agent-toolkit. Do not edit.
// A test regenerates it and fails if the toolkit's schema has drifted.
export const CREATE_REFUND_INPUT_SCHEMA = {
  type: 'object',
  properties: {
    capture_id: {
      type: 'string',
      pattern: '^[A-Za-z0-9_-]{15,32}$',
      description: 'The ID of the capture to refund.',
    },
    amount: {
      type: 'object',
      properties: {
        currency_code: {
          type: 'string',
        },
        value: {
          type: 'string',
        },
      },
      required: ['currency_code', 'value'],
      additionalProperties: false,
      description: 'The amount to refund. If not specified, the full captured amount is refunded.',
    },
    invoice_id: {
      type: 'string',
      pattern: '^[A-Za-z0-9_-]{1,127}$',
      description: 'The invoice ID that is used to track this payment.',
    },
    note_to_payer: {
      type: 'string',
      description: 'A note to the payer.',
    },
  },
  required: ['capture_id'],
  additionalProperties: false,
} as const
